name: CI Workflow

on:
  push:
    branches:
      - lab2
      - lab3
      - lab2_autotests*
      - lab3_autotests*
  pull_request:
    branches:
      - lab2
      - lab3
      - lab2_autotests*
      - lab3_autotests*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m playwright install chromium --with-deps
          
      - name: Start FastAPI Application Server
        run: |
          python -m uvicorn app.main:app --host 0.0.0.0 --port 8181 &
          sleep 5

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --junitxml=test_report.xml || true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test_result
          path: test_report.xml

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        continue-on-error: true
        with:
          dockerfile: Dockerfile

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/alexchirkova/catty-reminders-app
          tags: |
            type=ref,event=branch
            type=sha,prefix=,suffix=,format=long
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ id.meta.outputs.tags }}
          labels: ${{ id.meta.outputs.labels }}
